# Generated by Django 4.1 on 2022-10-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=25)),
                ('fist_name', models.CharField(max_length=25)),
                ('usufruct', models.IntegerField()),
                ('date_form', models.CharField(max_length=25)),
                ('date_to', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
