# Generated by Django 4.1 on 2022-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestsLicense', '0002_alter_requestslicense_date_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestslicense',
            name='usufruct',
            field=models.IntegerField(),
        ),
    ]
