# Generated by Django 4.1 on 2022-09-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestsLicense', '0003_alter_requestslicense_usufruct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestslicense',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
