# Generated by Django 4.1 on 2022-09-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestsLicense', '0004_alter_requestslicense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestslicense',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
